services:
  vision:
    build: .
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./videos:/app/videos
      - ./models:/app/models
      - ./data:/app/data
